// Original side stories: the protagonists and supporting cast below are invented.
export const ADVENTURE_PRESETS = [
  {
    "id": "naruto",
    "world": "Naruto",
    "charName": "Ren Aoki",
    "charTitle": "Entregador de uma vila pequena",
    "charAge": "21",
    "genre": "Mistério ninja",
    "hook": "Uma encomenda sem destinatário começa a ser seguida por desconhecidos.",
    "charBg": "Criado entre comerciantes, conhece estradas e atalhos. Nunca pertenceu a um clã famoso.",
    "charPersonality": "Observador, leal e receoso de decepcionar os outros.",
    "charSkills": "Orientação, corrida, esconder encomendas e primeiros socorros básicos. Sem técnicas especiais.",
    "supportingCast": "Mika, dona da hospedaria, confiou a entrega a você. Um viajante desconhecido quer comprar o pacote.",
    "storyStartPoint": "A carroça range na saída da vila e a poeira entra na boca. O pacote sem nome pesa no colo quando um homem para junto da roda, perto demais, e não tira os olhos da encomenda. Ele estende a mão como se o pacote já fosse dele.",
    "narration": { "style": "cinematic", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  },
  {
    "id": "one-piece",
    "world": "One Piece",
    "charName": "Lia Maré",
    "charTitle": "Aprendiz de carpinteira naval",
    "charAge": "23",
    "genre": "Mar e liberdade",
    "hook": "Um barco abandonado chega ao cais com reparos feitos por alguém desaparecido.",
    "charBg": "Trabalha em um estaleiro modesto e sonha conhecer outras ilhas. Não tem recompensa nem tripulação famosa.",
    "charPersonality": "Inventiva, teimosa e generosa.",
    "charSkills": "Reparo de barcos, nós, natação e ferramentas. Sem fruta especial ou poderes extraordinários.",
    "supportingCast": "Bento, seu patrão, quer desmontar o barco antes do amanhecer. Iara, pescadora local, reconhece a embarcação.",
    "storyStartPoint": "A água fria sobe pelos tornozelos enquanto você ajoelha no casco que deveria desmontar. Sob a tábua solta, os dedos encontram um papel úmido — um pedido de ajuda, ainda legível. Atrás de você, o martelo de Bento já bate no convés: antes do amanhecer, o barco some.",
    "narration": { "style": "light", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  },
  {
    "id": "harry-potter",
    "world": "Harry Potter",
    "charName": "Clara Vale",
    "charTitle": "Auxiliar de uma loja de objetos mágicos",
    "charAge": "24",
    "genre": "Mistério mágico",
    "hook": "Um objeto aparentemente comum começa a devolver cartas que nunca foram enviadas.",
    "charBg": "Concluiu sua formação mágica e trabalha catalogando objetos usados. Não pertence a nenhuma família importante.",
    "charPersonality": "Curiosa, cuidadosa e pouco à vontade com confrontos.",
    "charSkills": "Feitiços cotidianos, catalogação e observação. Magia limitada à formação comum, sem dons únicos.",
    "supportingCast": "Dora, proprietária da loja, exige discrição. Um cliente chamado Elias afirma que o objeto lhe pertence.",
    "storyStartPoint": "O cadeado da loja ainda está frio na palma quando a gaveta lacrada cede e uma carta cai no seu colo. O papel cheira a fuligem; o endereço escrito é o da sua própria casa. Do outro lado da vitrine, um homem não vai embora.",
    "narration": { "style": "literary", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  },
  {
    "id": "star-wars",
    "world": "Star Wars",
    "charName": "Taren Voss",
    "charTitle": "Mecânico de cargueiros",
    "charAge": "29",
    "genre": "Fronteira espacial",
    "hook": "Um conserto simples revela um passageiro escondido no casco.",
    "charBg": "Vive de pequenos reparos em um porto distante. Quer pagar suas dívidas e manter a oficina aberta.",
    "charPersonality": "Prático, desconfiado e incapaz de abandonar alguém ferido.",
    "charSkills": "Mecânica, leitura de sistemas e pilotagem básica. Sem ligação especial com a Força.",
    "supportingCast": "Nemi, sua fornecedora, cobra peças atrasadas. O capitão do cargueiro insiste que você não abra o compartimento.",
    "storyStartPoint": "O painel do casco aquece contra o ombro enquanto você aperta o último parafuso. Três batidas vêm de um compartimento sem registro — ritmadas, humanas. O capitão já está no corredor e a ordem é clara: não abra.",
    "narration": { "style": "cinematic", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  },
  {
    "id": "witcher",
    "world": "The Witcher",
    "charName": "Mila dos Juncos",
    "charTitle": "Ajudante de boticário",
    "charAge": "27",
    "genre": "Fantasia sombria",
    "hook": "Uma doença na aldeia começa a seguir a rota de um comerciante.",
    "charBg": "Aprendeu a reconhecer plantas e tratar ferimentos com uma curandeira. É humana comum, sem treinamento de bruxo.",
    "charPersonality": "Paciente, cética e protetora dos vizinhos.",
    "charSkills": "Herbalismo básico, curativos, negociação e trilhas locais. Sem magia ou mutações.",
    "supportingCast": "Oren, moleiro local, esconde uma compra recente. Sua mentora Ada pede que você procure a origem da água turva.",
    "storyStartPoint": "Você ainda está descalça no limiar quando o frasco frio toca a palma — a criança já correu. A água brilha no escuro da cozinha, turva, com o cheiro da fonte da aldeia. Do outro lado da rua, alguém tosse e o som não cessa.",
    "narration": { "style": "dark", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  },
  {
    "id": "skyrim",
    "world": "Skyrim",
    "charName": "Edda Freixo",
    "charTitle": "Carregadora de caravanas",
    "charAge": "25",
    "genre": "Estradas e ruínas",
    "hook": "Uma caravana desaparecida deixou todas as mercadorias para trás.",
    "charBg": "Viaja por trabalho e envia dinheiro à família. Não é escolhida por profecias e ninguém a conhece fora da estrada.",
    "charPersonality": "Resistente, franca e cautelosa com promessas fáceis.",
    "charSkills": "Acampar, rastrear carroças, usar machado de trabalho e cuidar de animais. Sem gritos ou poderes especiais.",
    "supportingCast": "Rurik, chefe da caravana, oferece pagamento para recuperar um livro de entregas. Sela, outra carregadora, quer desistir.",
    "storyStartPoint": "O vento da montanha entra pelas mangas quando você alcança as carroças — intactas, as rédeas ainda presas. O caldo na panela ainda aquece os dedos; não há ninguém para reclamá-lo. Sela puxa o seu braço, mas o livro de entregas está aberto sobre o banco, à espera.",
    "narration": { "style": "epic", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  },
  {
    "id": "pokemon",
    "world": "Pokémon",
    "charName": "Nico Prado",
    "charTitle": "Auxiliar de um abrigo Pokémon",
    "charAge": "20",
    "genre": "Exploração e amizade",
    "hook": "Os Pokémon do abrigo se recusam a atravessar a mesma ponte.",
    "charBg": "Cuida de animais resgatados e realiza entregas curtas. Não é campeão nem tem parentesco com treinadores famosos.",
    "charPersonality": "Gentil, persistente e curioso.",
    "charSkills": "Cuidados básicos, orientação e leitura de comportamento. Seu companheiro é um Pokémon comum, sem habilidade excepcional.",
    "supportingCast": "Bia, responsável pelo abrigo, pede que você encontre uma cuidadora atrasada. Um morador ouviu barulho sob a ponte.",
    "storyStartPoint": "A correia estica no pulso — seu companheiro recusa o primeiro degrau da ponte. O cheiro de rio molhado sobe, e entre as pedras uma mochila balança, ainda presa. Abaixo, a água se mexeu.",
    "narration": { "style": "light", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  },
  {
    "id": "westeros",
    "world": "Westeros — Crônicas de Gelo e Fogo",
    "charName": "Tomás Reedle",
    "charTitle": "Ajudante de uma estalagem",
    "charAge": "22",
    "genre": "Intriga e sobrevivência",
    "hook": "Um hóspede deixa uma bolsa e dois grupos diferentes vêm buscá-la.",
    "charBg": "Filho de trabalhadores, serve mesas e cuida dos cavalos. Não possui título, influência ou parentes nobres.",
    "charPersonality": "Discreto, pragmático e dividido entre segurança e lealdade.",
    "charSkills": "Cuidar de cavalos, escutar conversas, cozinhar e conhecer caminhos locais. Sem treinamento militar.",
    "supportingCast": "Mara, a estalajadeira, quer evitar problemas. Ivo, um cocheiro conhecido, pede que você esconda a bolsa.",
    "storyStartPoint": "A bolsa ainda está quente do ombro de quem a deixou quando Ivo a empurra contra o seu peito, no corredor fechado. O cheiro de cerveja azeda e palha sobe da cozinha; Mara ainda não abriu as portas. Do pátio, duas vozes diferentes já perguntam pelo mesmo hóspede — e Ivo murmura o dobro do seu salário para você mentir.",
    "narration": { "style": "intimate", "length": "balanced", "pace": "balanced" },
    "isKnownIP": true,
    "isExistingChar": false,
    "ordinaryCharacter": true,
    "worldBg": "Aventura original paralela, sem data canônica específica. Permaneça na física, nos lugares e no sistema de poder deste mundo; não atribua estes acontecimentos à obra oficial.",
    "charLore": "",
    "charAppearanceNote": "",
    "relationships": {},
    "gameStyle": "aventura",
    "useImages": true
  }
];
